homepage: "https://pybamm.org"
main_repo: "https://github.com/pybamm-team/PyBaMM"
language: python
primary_contact: "pybamm@pybamm.org"
auto_ccs:
  - "pybamm@pybamm.org"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined