homepage: "https://www.aeon-toolkit.org"
language: python
primary_contact: "contact@aeon-toolkit.org"
auto_ccs: []
sanitizers:
  - address
  - memory:
      experimental: True
  - undefined
fuzzing_engines:
  - libfuzzer
main_repo: "https://github.com/aeon-toolkit/aeon"
