homepage: "https://jupyter.org"
language: python
primary_contact: "jupyter@googlegroups.com"
auto_ccs:
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - memory:
     experimental: True
  - undefined
main_repo: "https://github.com/jupyterlab/jupyterlab"