homepage: "https://deepforest.readthedocs.io/"
language: python
primary_contact: 'benweinstein2010@gmail.com'
auto_ccs:
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - memory:
     experimental: True
  - undefined
main_repo: "https://github.com/weecology/deepforest"